name: Z1-build-one-test

on:
  workflow_dispatch:
    inputs:

      board:
        description: '设备型号'
        required: true
        type: choice
        options:
          - fine3399
          - firefly-rk3399
          - rk-sapphire
          - rock-4b
          - nanopim4v2
          - nanopct4
          - fmx1
          - aio-3399c-ai
          - verypc-d039
          - yskj
          - dg3399
        default: "aio-3399c-ai"

      version:
        description: 'Armbian 版本'
        required: true
        type: choice
        options:
          - v24.11
          - v25.02
          - v25.05
          - v25.8.0-trunk.460
          - v25.11.0-trunk.3
          - main
        default: v25.02

      branch:
        description: '系统分支'
        required: true
        type: choice
        options:
          - current
          - edge
          - vendor
        default: current

      release:
        description: '选择系统版本'
        required: true
        type: choice
        options:
          - 'Debian11 🎯 >> Bullseye'
          - 'Debian12 📚 >> Bookworm'
          - 'Debian13 🎪 >> Trixie'
          - 'Ubuntu22.04 🪼 >> Jammy'
          - 'Ubuntu24.04 🐜 >> Noble'
          - 'Ubuntu25.04 🐧 >> Plucky'
        default: 'Debian12 📚 >> Bookworm'

      system:
        description: '系统类型'
        required: true
        type: choice
        options:
          - minimal
          - server
          - desktop
        default: minimal

      desktop:
        description: '桌面类型（如果系统类型选择桌面）'
        required: false
        type: choice
        options:
          - xfce
          - cinnamon
          - gnome
          - i3-wm
        default: xfce

      bspfreeze:
        description: '冻结 BSP'
        required: false
        type: choice
        options:
          - 'yes'
          - 'no'
        default: 'yes'

      rootfs:
        description: 'ROOTFS 分区格式'
        required: false
        type: choice
        options:
          - ext4
          - btrfs
        default: btrfs

      vendor:
        description: '源码支持'
        required: false
        type: choice
        options:
          - Armbian
          - Armbian-unofficial
        default: Armbian

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:

      - name: 检查磁盘可用空间
        run: |
          echo "清理前的磁盘空间:"
          df -h
          sudo rm -rf /usr/local/.ghcup
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo rm -rf /usr/local/lib/android/sdk/ndk
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          sudo apt-get clean
          echo "清理后的磁盘空间:"
          df -h

      - name: 安装所需的软件包
        run: |
          sudo -E apt-get -y update
          sudo -E apt-get -y purge azure-cli ghc* zulu* llvm* firefox google* dotnet* powershell openjdk* mongodb* moby* || true
          sudo -E apt-get -y install neofetch btrfs-progs $(curl -fsSL https://tinyurl.com/ubuntu2204-build-armbian)
          sudo -E systemctl daemon-reload
          # sudo -E apt-get -y full-upgrade
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          echo 加载 Btrfs 内核模块
          sudo modprobe btrfs
          echo 确认模块已加载
          lsmod | grep btrfs
          echo 检查内核是否支持
          grep BTRFS /boot/config-$(uname -r)

      - name: 显示主机信息
        run: |
          neofetch --off --color_blocks off --stdout

          echo -e "\033[32mCPU info:\033[0m"
          lscpu

          echo -e "\033[32mMemory info:\033[0m"
          free -h

          echo -e "\033[32mDisk space info:\033[0m"
          df -hT ${PWD}

      - name: 检出目标
        uses: actions/checkout@v4

      - name: 检出 Armbian 源码
        run: |
          git clone -q --single-branch --depth=1 --branch=${{ inputs.version }} https://github.com/armbian/build.git

      - name: 复制 USERPATCHES 内容到源码根目录
        run: |
          cp -rvf userpatches build/
          # 修改rootfs 分区位置
          # sed -i 's|setenv rootdev "/dev/mmcblk0p1"|setenv rootdev "/dev/mmcblk0p2"|g' build/config/bootscripts/boot-rockchip.cmd
          # 修改日志等级为最高
          sed -i 's/\bverbosity=1\b/verbosity=7/g' build/config/bootenv/rockchip64.txt
          # cp -f rockchip64_common.inc.txt build/config/sources/families/include/rockchip64_common.inc
          # sed -i 's|https://github.com/armbian/rkbin|https://github.com/wingonwu/rkbin|g' build/extensions/rkbin-tools.sh
          # grep 'wingonwu/rkbin' build/extensions/rkbin-tools.sh

      - name: 设置系统类型
        env:
          DESKTOP_APPGROUPS: "browsers chat desktop_tools editors email internet multimedia office programming remote_desktop"
        run: |
          if [ "${{ inputs.system }}" == "minimal" ]; then
            echo "Setting up for minimal system..."
            SYSTEM_ARGS="BUILD_DESKTOP=no BUILD_MINIMAL=yes"
          elif [ "${{ inputs.system }}" == "server" ]; then
            echo "Setting up for server system..."
            SYSTEM_ARGS="BUILD_DESKTOP=no BUILD_MINIMAL=no"
          elif [ "${{ inputs.system }}" == "desktop" ]; then
            echo "Setting up for desktop system..."
            SYSTEM_ARGS="BUILD_DESKTOP=yes BUILD_MINIMAL=no DESKTOP_ENVIRONMENT=${{ inputs.desktop }} \
                  DESKTOP_ENVIRONMENT_CONFIG_NAME=config_base \
                  DESKTOP_APPGROUPS_SELECTED=\"${{ env.DESKTOP_APPGROUPS }}\""
          fi
          echo "BUILD_ARGS=$SYSTEM_ARGS" >> $GITHUB_ENV

      - name: 显示选择所要编译的的系统类型
        run: |
          echo "env.BUILD_ARGS: ${{ env.BUILD_ARGS }}"
          echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
          echo "status=success" >> ${GITHUB_OUTPUT}


      - name: 提取系统代号
        run: |
          # 使用awk提取最后一个>>之后的部分
          RELEASE_CODE=$(echo "${{ inputs.release }}"  | awk -F'>>' '{gsub(/^[ \t]+|[ \t]+$/, "", $2); print tolower($2)}')
          # 如果没有>>，则使用整个字符串（防止错误）
          if [ -z "$RELEASE_CODE" ]; then
          RELEASE_CODE="${{ inputs.release }}"
          fi
          echo "release_code=$RELEASE_CODE" >> $GITHUB_ENV

      - name: 显示系统代号
        run: |
          echo "env.release_code: ${{ env.release_code }}"

      - name: 编译 [ ${{ inputs.version }} - ${{ inputs.board }} - ${{ inputs.release }} - ${{ inputs.branch }} - ${{ inputs.system }} - ${{ inputs.rootfs }} ]
        run: |
          pushd build
          bash ./compile.sh build BOARD=${{ inputs.board }} \
          BRANCH=${{ inputs.branch }} \
          ${{ env.BUILD_ARGS }} \
          KERNEL_CONFIGURE=no \
          RELEASE=${{ env.release_code }} \
          COMPRESS_OUTPUTIMAGE=sha,img,xz \
          BSPFREEZE=${{ inputs.bspfreeze }} \
          ROOTFS_TYPE=${{ inputs.rootfs }} \
          VENDOR=${{ inputs.vendor }}
          popd

      - name: 显示剩余空间
        run: |
          df -hT ${PWD}

      - name: 显示镜像
        run: |
          ls -lh ${{ github.workspace }}/build/output/images
          echo "buildtime=$(date +"%Y.%m")" >> $GITHUB_ENV

      - name: 上传镜像
        uses: ncipollo/release-action@main
        if: success()
        with:
          tag: "${{ inputs.vendor }}_${{ inputs.version }}_${{ env.release_code }}_${{ inputs.branch }}_${{ inputs.system }}_b${{ env.buildtime }}"
          artifacts: "${{ github.workspace }}/build/output/images/*"
          allowUpdates: true
          removeArtifacts: false
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            ### 💿 Armbian 镜像信息
            - 💻 Armbian 版本: ${{ inputs.release }}
            - 🖥 系统分支：${{ inputs.branch }}
            - 🗂 源码: https://github.com/armbian/build.git
            - 🔖 源码分支: ${{ inputs.version }}
            - ⏱️ 编译时间: $(date +"%Y年%m月%d日%H时%M分")
            - 💽 ROOTFS 格式: ${{ inputs.rootfs }}
            ### ⚙ 设置信息
            - 👤 默认用户名:  root
            - 🔒 默认密码:  1234
            - ⌨ 修改 apt 源: armbian-apt
            - ⌨ 配置命令: armbian-config
            - ⌨ 升级命令: armbian-upgrade
            - ⌨ 安装命令: armbian-install 
          draft: false
          prerelease: false
